original_repo: https://github.com/hackcu/startups2students
edition: Fall 2019
s2s_date: November 7th
startups_apply: https://docs.google.com/forms/d/e/1FAIpQLSeX6sBXrXrVPCm10dbe2GbgOEGO-KDDoiyct7l4bvw98r5o3A/viewform
fb_event: https://www.facebook.com/events/483888339130907/

sass:
    sass_dir: assets/_sass
    style: compressed
