original_repo: https://github.com/hackcu/startups2students
edition: Fall 2018
s2s_date: October 23rd
startups_apply: https://hackcu.typeform.com/to/IlDBwe
fb_event: https://www.facebook.com/events/1980541438904389/

sass:
    sass_dir: assets/_sass
    style: compressed