original_repo: https://github.com/hackcu/startups2students
edition: Fall 2019
s2s_date: October 17th
startups_apply: https://hackcu.typeform.com/to/IlDBwe
fb_event: https://www.facebook.com/events/483888339130907/

sass:
    sass_dir: assets/_sass
    style: compressed